on:
  push:
    branches:
      - 'master'
name: Build
jobs:
  build_extension:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: Build v2 and v3
        run: npm run build
      - name: Upload v2
        uses: actions/upload-artifact@v3
        with:
          name: extension-manifest-v2
          path: dist/v2
      - name: Upload v3
        uses: actions/upload-artifact@v3
        with:
          name: extension-manifest-v3
          path: dist/v3

  release_extension:
    if: 'true'
    needs: [build_extension]
    runs-on: ubuntu-latest
    steps:
      - name: Download v2
        uses: actions/download-artifact@v3
        with:
          name: extension-manifest-v2
          path: dist/v2
      - name: Download v2
        uses: actions/download-artifact@v3
        with:
          name: extension-manifest-v2
          path: dist/v3
      - name: Zip dist v2
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          directory: ./dist/v2
          path: .
          filename: ../../dist-v2.zip
      - name: Zip dist v3
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          directory: ./dist/v3
          path: .
          filename: ../../dist-v3.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload v2 Release Asset
        id: upload-release-asset-v2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist-v2.zip
          asset_name: extension-manifest-v2.zip
          asset_content_type: application/zip
      - name: Upload v3 Release Asset
        id: upload-release-asset-v3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist-v3.zip
          asset_name: extension-manifest-v3.zip
          asset_content_type: application/zip


